title: Ce n'est pas ce qu'il semble
author: Carlos Salinas
email: carlos-e-salinas@protonmail.com
description: > # this means to ignore newlines until "twitter_username:"
  A small portfolio to showcase my work.

# social links
twitter_username: cdrlos
github_username:  cdrlos
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

markdown: kramdown
kramdown:
  math_engine: katex
  math_engine_opts: {}
  syntax_highlighter: rouge
  syntax_highlighter_opts: {}

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jemoji
 - kramdown-math-katex

exclude:
  - archive
